export const StatusCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DEVICE_MISMATCH: "DEVICE_MISMATCH",
  SUBSCRIBER_ID_NOT_FOUND: "SUBSCRIBER_ID_NOT_FOUND",
  SUBSCRIBER_ID_NOT_OWNED: "SUBSCRIBER_ID_NOT_OWNED",
  SUBSCRIBER_ID_IN_USE: "SUBSCRIBER_ID_IN_USE",
  USER_ALREADY_SUBSCRIBED: "USER_ALREADY_SUBSCRIBED",
};
